In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://www.googleapis.com/auth/spreadsheets',
         'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name('gs_credentials.json', scope)
client = gspread.authorize(credentials)

spreadsheet = client.open_by_url("https://docs.google.com/spreadsheets/d/155eZnfku7_zMkiy967vqSPvqo4xuAFa86b2wBN7p0_s/edit?usp=sharing")

In [2]:
import pandas as pd
# Get the first worksheet by index
worksheet = spreadsheet.get_worksheet(0)

# Or get by name
# worksheet = spreadsheet.worksheet("Sheet1")
# With the worksheet selected, you can now fetch all the data:

# Get all records as a list of dictionaries
records = worksheet.get_all_records()

# Convert records to a DataFrame
df = pd.DataFrame(records)

# Display the DataFrame
print(df.head())

GSpreadException: the header row in the worksheet is not unique, try passing 'expected_headers' to get_all_records

In [8]:
df = pd.read_excel('hsk_vocab.xlsx', sheet_name='HSK1')
df.head()

,id,vocab,vocab_pinyin,vocab_trans_vi,vocab_trans_en,example,example_pinyin,example_trans_vi,example_trans_vi.1
0,1,爱,ài,yêu,Love,我爱你。,Wǒ ài nǐ.,Tôi yêu bạn.,I love you.
1,2,八,bā,tám,eight,他有八个苹果。,Tā yǒu bā ge píngguǒ.,Anh ấy có tám quả táo.,He has eight apples.
2,3,爸爸,bàba,bố,dad,我的爸爸很高。,Wǒ de bàba hěn gāo.,Bố của tôi rất cao.,My father is very tall.
3,4,杯子,bēizi,cốc,glass,这是我的杯子。,Zhè shì wǒ de bēizi.,Đây là cốc của tôi.,This is my cup.
4,5,北京,Běijīng,Bắc Kinh,Beijing,北京很大。,Běijīng hěn dà.,Bắc Kinh thì lớn.,Beijing is big.

In [16]:
df = pd.DataFrame()
for i in range(1,7):
    dft = pd.read_excel('hsk_vocab.xlsx', sheet_name=f'HSK{i}')
    dft['level'] = i
    df = pd.concat([df, dft])
df.shape

(5002, 10)

In [17]:
df.isna().sum()

id                  0
vocab               0
vocab_pinyin        0
vocab_trans_vi      0
vocab_trans_en      0
example             0
example_pinyin      0
example_trans_vi    1
example_trans_en    1
level               0
dtype: int64

In [18]:
df.head()

,id,vocab,vocab_pinyin,vocab_trans_vi,vocab_trans_en,example,example_pinyin,example_trans_vi,example_trans_en,level
0,1,爱,ài,yêu,Love,我爱你。,Wǒ ài nǐ.,Tôi yêu bạn.,I love you.,1
1,2,八,bā,tám,eight,他有八个苹果。,Tā yǒu bā ge píngguǒ.,Anh ấy có tám quả táo.,He has eight apples.,1
2,3,爸爸,bàba,bố,dad,我的爸爸很高。,Wǒ de bàba hěn gāo.,Bố của tôi rất cao.,My father is very tall.,1
3,4,杯子,bēizi,cốc,glass,这是我的杯子。,Zhè shì wǒ de bēizi.,Đây là cốc của tôi.,This is my cup.,1
4,5,北京,Běijīng,Bắc Kinh,Beijing,北京很大。,Běijīng hěn dà.,Bắc Kinh thì lớn.,Beijing is big.,1

In [20]:
df.to_csv('hsk_vocab_full.csv', index=False)

In [8]:
df.shape

(592, 7)

In [9]:
df_export = df.iloc[:, [0,1,3,4,5]]
df_export.head()

  Word     Pinyin    Meaning  Level  Lecture
0  一 斤      yijin  One pound      1        1
1   昨天    zuotian  yesterday      1        1
2  星期五  xingqi wu     Friday      1        1
3   身体     shenti       Body      1        1
4   一周    yi zhou     a week      1        1

In [10]:
df_export.to_csv('data.csv', index=False)

In [12]:
'zhī'

'zhī'